version: '2'

networks:
  byfn:

volumes:
  peer1.beta.com:
  
services:
  couchdb.peer1.beta.com:
    container_name: couchdb.peer1.beta.com
    image: hyperledger/fabric-couchdb:0.4.18
    hostname: couchdb.peer1.beta.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - byfn    

  peer1.beta.com:
    container_name: peer1.beta.com
    hostname: peer1.beta.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer1.beta.com
      - CORE_PEER_ADDRESS=peer1.beta.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.beta.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.beta.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.beta.com:8051
      - CORE_PEER_LOCALMSPID=BetaMSP
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_SHIM=DEBUG
      - CORE_LOGGING_CAUTHDSL=warning
      - CORE_LOGGING_GOSSIP=warning
      - CORE_LOGGING_LEDGER=info
      - CORE_LOGGING_MSP=warning
      - CORE_LOGGING_POLICIES=warning
      - CORE_LOGGING_GRPC=error
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      # Client certs
      #- CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin.beta.com/tls/tlsca.crt
      #- CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin.beta.com/tls/server.crt
      #- CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin.beta.com/tls/server.key

      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.beta.com:5984
      - GODEBUG=netdns=go

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start  
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beta.com/peers/peer1.beta.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beta.com/peers/peer1.beta.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/beta.com/users:/var/hyperledger/users
        - peer1.beta.com:/var/hyperledger/production
        
    ports:
      - 8051:8051
      - 8443:8443
    networks: 
      - byfn  

  cli-peer1-beta.com:
    extends:
      file: docker-compose-cli-peer1-beta.yaml            
      service: cli-peer1-beta.com
    depends_on:      
      - peer1.beta.com        
