#set -ev
#!/bin/sh

# Taking Inputs from .env file
set -a
[ -f .env ] && . .env
set +a

pwd

export ORGANIZATION_NAME_LOWERCASE=`echo "$ORGANIZATION1_NAME" | tr '[:upper:]' '[:lower:]'`

echo "##################################################################################"
echo "################### Creating Orderer and Peer docker files #######################"
echo "##################################################################################"
if [ $NETWORK_TYPE == "single" ];then
    # editing orderer files.
    if [ $ORDERER_FLAG == "true" ];then
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-orderer1_temp.yaml > ./docker/docker-compose-orderer1.yaml
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-orderer2_temp.yaml > ./docker/docker-compose-orderer2.yaml
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-orderer3_temp.yaml > ./docker/docker-compose-orderer3.yaml
    fi
    # peer files
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-peer0-org1_template.yaml > ./docker/docker-compose-peer0-$ORGANIZATION_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-peer1-org1_template.yaml > ./docker/docker-compose-peer1-$ORGANIZATION_NAME_LOWERCASE.yaml
    
    # cli files 
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-cli-peer0-org1_temp.yaml > ./docker/docker-compose-cli-peer0-$ORGANIZATION_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' templates/single/docker-compose-cli-peer1-org1_temp.yaml > ./docker/docker-compose-cli-peer1-$ORGANIZATION_NAME_LOWERCASE.yaml

else
    if [ $ORDERER_FLAG == "true" ];then
        # editing orderer files.
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-orderer1_temp.yaml > ./docker/docker-compose-orderer1.yaml    
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-orderer2_temp.yaml > ./docker/docker-compose-orderer2.yaml
        sed -e 's/orderer_organization_name/'$NAME_OF_ORD_ORG'/g' -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-orderer3_temp.yaml > ./docker/docker-compose-orderer3.yaml
    fi
    # org1 peer files
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-peer0-org1_template.yaml > ./docker/docker-compose-peer0-$ORGANIZATION_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-peer1-org1_template.yaml > ./docker/docker-compose-peer1-$ORGANIZATION_NAME_LOWERCASE.yaml

    # org2 peer files
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization2_name/'$ORGANIZATION2_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-peer0-org2_template.yaml > ./docker/docker-compose-peer0-$ORGANIZATION2_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization2_name/'$ORGANIZATION2_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-peer1-org2_template.yaml > ./docker/docker-compose-peer1-$ORGANIZATION2_NAME_LOWERCASE.yaml

    # org1 cli file
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-cli-peer0-org1_temp.yaml > ./docker/docker-compose-cli-peer0-$ORGANIZATION_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization_name/'$ORGANIZATION1_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-cli-peer1-org1_temp.yaml > ./docker/docker-compose-cli-peer1-$ORGANIZATION_NAME_LOWERCASE.yaml

    #org2 cli file
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization2_name/'$ORGANIZATION2_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-cli-peer0-org2_temp.yaml > ./docker/docker-compose-cli-peer0-$ORGANIZATION2_NAME_LOWERCASE.yaml
    sed -e 's/orderer_organization_domain/'$DOMAIN_OF_ORDERER_ORGANIZATION'/g' -e 's/organization2_name/'$ORGANIZATION2_NAME'/g' -e 's/orderer1_ip/'$ORDERER1_IP'/g' -e 's/orderer2_ip/'$ORDERER2_IP'/g' -e 's/orderer3_ip/'$ORDERER3_IP'/g' -e 's/organization_small_name/'$ORGANIZATION_NAME_LOWERCASE'/g' -e 's/organization2_small_name/'$ORGANIZATION2_NAME_LOWERCASE'/g' -e 's/organization_domain/'$DOMAIN_OF_ORGANIZATION'/g' -e 's/organization2_domain/'$DOMAIN_OF_ORGANIZATION2'/g' -e 's/peer0_org1_ip/'$PEER0_ORG1_IP'/g' -e 's/peer1_org1_ip/'$PEER1_ORG1_IP'/g' -e 's/peer0_org2_ip/'$PEER0_ORG2_IP'/g' -e 's/peer1_org2_ip/'$PEER1_ORG2_IP'/g' templates/multiple/docker-compose-cli-peer1-org2_temp.yaml > ./docker/docker-compose-cli-peer1-$ORGANIZATION2_NAME_LOWERCASE.yaml

fi    

echo "###################################################################################"
echo "################### Completed Orderer and Peer docker files #######################"
echo "###################################################################################"
